# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.exposures_bundle_cmaq_cmaq_output import ExposuresBundleCmaqCmaqOutput  # noqa: F401,E501
from swagger_server import util


class ExposuresBundleCmaqValues(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, variable: str=None, cmaq_output: List[ExposuresBundleCmaqCmaqOutput]=None):  # noqa: E501
        """ExposuresBundleCmaqValues - a model defined in Swagger

        :param variable: The variable of this ExposuresBundleCmaqValues.  # noqa: E501
        :type variable: str
        :param cmaq_output: The cmaq_output of this ExposuresBundleCmaqValues.  # noqa: E501
        :type cmaq_output: List[ExposuresBundleCmaqCmaqOutput]
        """
        self.swagger_types = {
            'variable': str,
            'cmaq_output': List[ExposuresBundleCmaqCmaqOutput]
        }

        self.attribute_map = {
            'variable': 'variable',
            'cmaq_output': 'cmaq_output'
        }

        self._variable = variable
        self._cmaq_output = cmaq_output

    @classmethod
    def from_dict(cls, dikt) -> 'ExposuresBundleCmaqValues':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExposuresBundle_cmaq_values of this ExposuresBundleCmaqValues.  # noqa: E501
        :rtype: ExposuresBundleCmaqValues
        """
        return util.deserialize_model(dikt, cls)

    @property
    def variable(self) -> str:
        """Gets the variable of this ExposuresBundleCmaqValues.


        :return: The variable of this ExposuresBundleCmaqValues.
        :rtype: str
        """
        return self._variable

    @variable.setter
    def variable(self, variable: str):
        """Sets the variable of this ExposuresBundleCmaqValues.


        :param variable: The variable of this ExposuresBundleCmaqValues.
        :type variable: str
        """

        self._variable = variable

    @property
    def cmaq_output(self) -> List[ExposuresBundleCmaqCmaqOutput]:
        """Gets the cmaq_output of this ExposuresBundleCmaqValues.


        :return: The cmaq_output of this ExposuresBundleCmaqValues.
        :rtype: List[ExposuresBundleCmaqCmaqOutput]
        """
        return self._cmaq_output

    @cmaq_output.setter
    def cmaq_output(self, cmaq_output: List[ExposuresBundleCmaqCmaqOutput]):
        """Sets the cmaq_output of this ExposuresBundleCmaqValues.


        :param cmaq_output: The cmaq_output of this ExposuresBundleCmaqValues.
        :type cmaq_output: List[ExposuresBundleCmaqCmaqOutput]
        """

        self._cmaq_output = cmaq_output
