# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.exposures_bundle_cmaq_values import ExposuresBundleCmaqValues  # noqa: F401,E501
from swagger_server import util


class ExposuresBundleCmaq(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, values: List[ExposuresBundleCmaqValues]=None):  # noqa: E501
        """ExposuresBundleCmaq - a model defined in Swagger

        :param values: The values of this ExposuresBundleCmaq.  # noqa: E501
        :type values: List[ExposuresBundleCmaqValues]
        """
        self.swagger_types = {
            'values': List[ExposuresBundleCmaqValues]
        }

        self.attribute_map = {
            'values': 'values'
        }

        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'ExposuresBundleCmaq':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExposuresBundle_cmaq of this ExposuresBundleCmaq.  # noqa: E501
        :rtype: ExposuresBundleCmaq
        """
        return util.deserialize_model(dikt, cls)

    @property
    def values(self) -> List[ExposuresBundleCmaqValues]:
        """Gets the values of this ExposuresBundleCmaq.


        :return: The values of this ExposuresBundleCmaq.
        :rtype: List[ExposuresBundleCmaqValues]
        """
        return self._values

    @values.setter
    def values(self, values: List[ExposuresBundleCmaqValues]):
        """Sets the values of this ExposuresBundleCmaq.


        :param values: The values of this ExposuresBundleCmaq.
        :type values: List[ExposuresBundleCmaqValues]
        """

        self._values = values
